### ISSUE TITLE
Basic auth blocked on Office 2016?

### ISSUE THREAD

**Issue by lean0x2F** [ryhanson/go-phish#11]
First of all, amazing tool :) I've been using it since you released it with great results.

In a recent phishing engagement, I noticed that all the victims using Office 2016 didn't enter their credentials. I tested myself using the last Office version and it seems that as soon as Word receives a 401 response, it simply drops the connection. 

I also tried using the external resource technique that CanaryTokens guys use, without success.

Any ideas?

Thank you!

**Comment by lean0x2F** [comment]
Closing this (inactivity)

**Comment by pinkLagoon** [comment]
Hello @lean0x2F were you able to resolve this issue?
