### ISSUE TITLE
Can't seem to get a prompt

### ISSUE THREAD

**Issue by turnerdb** [ryhanson/go-phish#8]
Greetings,

Just ran across your project and wanted to give it a try.  I think i may be doing something wrong as I do not get a prompt when opening the injected file.  I can as the file opens that it is contacting the url, but the document just opens.  Not sure if I missed something in the instructions or if you have any additional information you can pass along to get things working.

Do I need to set anything up special on the domain side of things?  The domain I used points to a publicly route-able IP.  Should I try using it on a cloud server instead of one that has to pass via DMZ?

Thanks!

OS: CentOS
Version: latest

**Comment by turnerdb** [comment]
Nevermind.  I got it to work.

**Comment by cha0tic87** [comment]
Having the same issue, how did you resolve this?

**Comment by pinkLagoon** [comment]
> Nevermind. I got it to work.

Would be very helpful to others if you could tell us how you fixed it.
